title: "Rustでリレーショナルデータベースを実装する"
summary: |
  Rustでリレーショナルデータベース(RDBMS)をゼロから実装して、データベースの動作原理を理解する本です。
topics: ["database", "rust"] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - 01_intro
