title: "RustでWasm Runtimeを実装しよう"
summary: |
  Rustで"Hello World"を出力できる小さなWasm Runtimeを実装して、Wasmがどのように動作しているのかを理解する本です。
  Wasm RuntimeはいわばJVMやRubyVMのようなもので、本書を最後まで読み実装することでVMがどのように動作しているのかも合わせて理解できます。
topics: ["wasm", "rust"] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - 01_intro
  - 02_about_wasm
  - 03_intro_wasm
  - 04_wasm_binary_structure
  - 05_how_decode_wasm_binary
  - 06_decode_function
  - 07_decode_function_param_result
