title: "RustでWasm Runtimeを書く"
summary: |
  Rustで"Hello World"を出力できる小さなWasm Runtimeを実装して、Wasmの動作原理を理解する本です。
topics: ["wasm", "rust"] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - 01_intro
  - 02_about_wasm
  - 03_intro_wasm
  - 04_wasm_binary_structure
  - 05_how_decode_wasm_binary
  - 06_decode_function_1
  - 07_decode_function_2
  - 08_how_function_execute
  - 09_build_runtime_1
  - 10_build_runtime_2
